### ISSUE TITLE
investigate missing timestamps

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#104]
from @sbabur:

> @onlyjsmith Hi Jonathan,
I’m not seeing a timestamp for the when Namibia forms were actually synced. Am I looking in the wrong place or did this disappear?
I only see the following:
> - recorded_on
> - initial_form_completion_duration_seconds
> - most_recent_form_completed_time
> - updated_at

**Comment by Nicolaidavies** [comment]
@sbabur 

The updated_at field is a timestamp of when the record was synced to the server.

**Comment by onlyjsmith** [comment]
@sbabur noted comment about updates - we're only investigating.

**Comment by Nicolaidavies** [comment]
@sbabur

The `updated_at` field is saved as a unix epoch (seconds since 1/1/1970). 

You should be able to convert it into a regular date using this guide: https://www.extendoffice.com/documents/excel/2473-excel-timestamp-to-date.html 

Take a look at the section labelled "Convert Timestamp To Date".

Let me know if you have any problems doing so.

**Comment by sbabur** [comment]
@TNgidi Can close - was able to use Nicolai's guidance

**Comment by onlyjsmith** [comment]
Thanks @sbabur
