### ISSUE TITLE
limit downloading of responses to filtered time periods

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#14]
For example, to match a given season start and end. 

We already have this capability on the server, but the client is not using it. We need to make sure we have a robust way to make sure we're not re-downloading the same responses multiple times.

**Comment by sbabur** [comment]
@onlyjsmith Checking in on reason this is Blocked

**Comment by onlyjsmith** [comment]
It’s on the ‘waiting’ side of ‘Waiting/blocked’ ;-) It’s just waiting for a timeslot to open up for us to work on it. We’re working at the moment on making it easier to check if configurations are valid when we save them, paving the way for user-driven configuration. We’ll aim to get to this following that.

**Comment by sbabur** [comment]
@onlyjsmith ok great - loading the data is always going to be a challenge for users trying to consult the dashboard. I'll be testing performance with fake data tomorrow. 

Other questions on how the system loads data:
1. Will the system accept the batches of records loaded, even if its not everything (say it got to 10,000 out of 50,000) and pnly download the remaining non-loaded ones upon hitting Retrieve again?Or does it have to have a fully successful retrieval in order to retrieve anything?

2. If I have retrieve 10,000 records and submit 100 forms - the Retrieve option grabs just those last 100, while the Re-retrieve option grabs all 10,100? Is my understanding correct?

**Comment by onlyjsmith** [comment]
1. We collect small batches of records from the server. It will display whatever it manages to get, and tell the user if the network request failed.
2. That’s correct. When you ‘Retrieve’ or ‘Re-retrieve’, it gets them in date-order from the server, and stores the ID of the last successfully-retrieved record. The difference is that ‘Retrieve’ uses that last_id, and says “give me everything after this ID”, which ‘Re-retrieve’ says “give me everything from the start”.

(Btw have moved to end of the ‘Ready for dev’ queue)

**Comment by TNgidi** [comment]
This ok to close. @onlyjsmith  I made a copy in our internal tickets board
