### ISSUE TITLE
every time we update seasons start_date we remove location_selection

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#49]

**Comment by onlyjsmith** [comment]
@sbabur We’re working on this now...

**Comment by sbabur** [comment]
@onlyjsmith You mean this? Can you deploy the fix to production when its ready?

![image](https://user-images.githubusercontent.com/37877007/40488490-3085b840-5f67-11e8-8add-1928f8cc1222.png)

**Comment by onlyjsmith** [comment]
Yes - we’ll hotfix in a few mins and will let you know.

**Comment by TNgidi** [comment]
@sbabur We have fixed this issue now on version 1.2.1 and it is already deployed on production and staging. This problem came in a while back when we were introducing seasons, but it is fixed now.
We would kindly ask that everyone upgrades to the version 1.2.1 because if anyone edits season dates on the old version (1.2.0) the bug will remove the location-selection the application again.

**Comment by sbabur** [comment]
@onlyjsmith @TNgidi Great, thanks both - will have our testers update

**Comment by onlyjsmith** [comment]
Thanks! Sorry for the inconvenience. We're working hard to make sure we don’t need to force users to update.

**Comment by sbabur** [comment]
@onlyjsmith Validated in v1.2.3 - can close
