### ISSUE TITLE
change WhatsApp number to a group

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#92]
Not certain if this is possible.

**Comment by onlyjsmith** [comment]
Links to #81

**Comment by sbabur** [comment]
@onlyjsmith Is it possible to send to a group? We discussed a limitation of the Groups being that anyone who messages the group would get added to the group, but I don't think we knew for sure? If it is possible the country teams said they would prefer to use a group, and then as people get added to the group as a result of sending messages, we would have the group admin remove them (CHAI person will volunteer for this) so that users do not get spammed

**Comment by onlyjsmith** [comment]
Let’s discuss on call this Thurs

**Comment by onlyjsmith** [comment]
Hi @sbabur - I caught up with @TNgidi and it sounds like once an admin kicks out a user from a group they cannot return. Since we'll want users to only be in the group (and get messages) when their support request is being handled, and we can't be certain they'll remove themselves, it sounds like this group approach can't work. 

Will also update #81, which relates.

**Comment by onlyjsmith** [comment]
WhatsApp groups won't work for our needs (too fiddly to remove users after they've had their query resolved, and then let them rejoin). Working instead on #81
